# Generated by Django 4.0.3 on 2022-12-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
