# Generated by Django 4.0.3 on 2022-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('sign_date', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=256)),
            ],
        ),
    ]
